Repository aws-ia/terraform-aws-eks-blueprints, pull requests merged in 2022-01, with the labels that each got.

#186 IRSA for AWS for Fluent Bit Add-on
  README.md
  docs/add-ons/aws-for-fluent-bit.md
  examples/1-eks-cluster-with-new-vpc/README.md
  main.tf
  modules/aws-eks-managed-node-groups/README.md
  modules/aws-eks-managed-node-groups/data.tf
  modules/aws-eks-managed-node-groups/iam.tf
  modules/aws-eks-self-managed-node-groups/README.md
  modules/aws-eks-self-managed-node-groups/data.tf
  modules/aws-eks-self-managed-node-groups/iam.tf
  modules/aws-kms/README.md
  modules/kubernetes-addons/README.md
  modules/kubernetes-addons/aws-for-fluentbit/README.md
  modules/kubernetes-addons/aws-for-fluentbit/data.tf
  modules/kubernetes-addons/aws-for-fluentbit/locals.tf
  modules/kubernetes-addons/aws-for-fluentbit/main.tf
  modules/kubernetes-addons/aws-for-fluentbit/outputs.tf
  modules/kubernetes-addons/aws-for-fluentbit/values.yaml
  modules/kubernetes-addons/aws-for-fluentbit/variables.tf
  modules/kubernetes-addons/main.tf
  modules/kubernetes-addons/variables.tf
Labels: enhancement

#195 refactor: platform team aws_iam_policy_document
  modules/aws-eks-teams/data.tf
  modules/aws-eks-teams/main.tf
Labels: enhancement

#192 Self-managed node groups update
  docs/node-groups.md
  eks-worker.tf
  examples/1-eks-cluster-with-new-vpc/main.tf
  examples/5-eks-cluster-with-windows-support/main.tf
  examples/8-eks-cluster-with-karpenter/main.tf
  modules/aws-eks-managed-node-groups/README.md
  modules/aws-eks-managed-node-groups/iam.tf
  modules/aws-eks-managed-node-groups/locals.tf
  modules/aws-eks-managed-node-groups/main.tf
  modules/aws-eks-managed-node-groups/managed-launch-templates.tf
  modules/aws-eks-managed-node-groups/outputs.tf
  modules/aws-eks-self-managed-node-groups/README.md
  modules/aws-eks-self-managed-node-groups/iam.tf
  modules/aws-eks-self-managed-node-groups/locals.tf
  modules/aws-eks-self-managed-node-groups/main.tf
  modules/aws-eks-self-managed-node-groups/self-managed-launch-templates.tf
  modules/aws-eks-teams/README.md
Labels: bug, documentation, enhancement

#194 test: add cluster endpoints settings, fix docs
  examples/6-eks-fully-private-eks-cluster/README.md
  examples/6-eks-fully-private-eks-cluster/main.tf
Labels: documentation, examples

#198 Issue, Feature Request and PR templates added
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  examples/6-eks-cluster-with-argocd/README.md
  examples/6-eks-cluster-with-argocd/outputs.tf
Labels: documentation

#206 Kics recommendations
  examples/analytics/spark-k8s-operator/README.md
  examples/analytics/spark-k8s-operator/main.tf
  modules/aws-eks-teams/main.tf
  modules/irsa/README.md
  modules/irsa/variables.tf
  modules/kubernetes-addons/README.md
  modules/kubernetes-addons/agones/README.md
  modules/kubernetes-addons/agones/variables.tf
  modules/kubernetes-addons/aws-coredns/README.md
  modules/kubernetes-addons/aws-coredns/variables.tf
  modules/kubernetes-addons/aws-ebs-csi-driver/README.md
  modules/kubernetes-addons/aws-ebs-csi-driver/variables.tf
  modules/kubernetes-addons/aws-for-fluentbit/README.md
  modules/kubernetes-addons/aws-for-fluentbit/data.tf
  modules/kubernetes-addons/aws-for-fluentbit/locals.tf
  modules/kubernetes-addons/aws-for-fluentbit/main.tf
  modules/kubernetes-addons/aws-for-fluentbit/variables.tf
  modules/kubernetes-addons/aws-kube-proxy/README.md
  modules/kubernetes-addons/aws-kube-proxy/variables.tf
  modules/kubernetes-addons/aws-load-balancer-controller/README.md
  modules/kubernetes-addons/aws-load-balancer-controller/main.tf
  modules/kubernetes-addons/aws-load-balancer-controller/outputs.tf
  modules/kubernetes-addons/aws-node-termination-handler/README.md
  modules/kubernetes-addons/aws-node-termination-handler/data.tf
  modules/kubernetes-addons/aws-node-termination-handler/main.tf
  modules/kubernetes-addons/aws-node-termination-handler/variables.tf
  modules/kubernetes-addons/aws-opentelemetry-eks/README.md
  modules/kubernetes-addons/aws-opentelemetry-eks/main.tf
  modules/kubernetes-addons/aws-opentelemetry-eks/variables.tf
  modules/kubernetes-addons/aws-vpc-cni/README.md
  modules/kubernetes-addons/aws-vpc-cni/variables.tf
  modules/kubernetes-addons/cluster-autoscaler/README.md
  modules/kubernetes-addons/cluster-autoscaler/variables.tf
  modules/kubernetes-addons/ingress-nginx/README.md
  modules/kubernetes-addons/ingress-nginx/variables.tf
  modules/kubernetes-addons/keda/README.md
  modules/kubernetes-addons/keda/main.tf
  modules/kubernetes-addons/keda/variables.tf
  modules/kubernetes-addons/main.tf
  modules/kubernetes-addons/prometheus/README.md
  modules/kubernetes-addons/prometheus/main.tf
  modules/kubernetes-addons/prometheus/variables.tf
  modules/kubernetes-addons/variables.tf
  modules/kubernetes-addons/yunikorn/README.md
  modules/kubernetes-addons/yunikorn/variables.tf
  modules/s3/README.md
  modules/s3/main.tf
  modules/s3/outputs.tf
  modules/s3/variables.tf
Labels: enhancement

#204 KICS Security Scan Github Action Workflow
  .github/workflows/kics-security-scan.yml
Labels: enhancement

#190 Documentation updates
  docs/add-ons/aws-for-fluent-bit.md
  docs/add-ons/cluster-autoscaler.md
  docs/add-ons/index.md
  docs/add-ons/metrics-server.md
  docs/add-ons/nginx.md
  docs/add-ons/spark-on-k8s-operator.md
  docs/add-ons/traefik.md
  docs/advanced/bottlerocket.md
  docs/core-concepts.md
  docs/getting-started.md
  docs/internal/ci.md
  docs/modules/emr-on-eks.md
  docs/node-groups.md
  docs/teams.md
  mkdocs.yml
  modules/aws-eks-teams/README.md
Labels: documentation

#218 PR Template fix
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/teams.md
Labels: bug
