Repository aws-ia/terraform-aws-eks-blueprints, pull requests merged in 2022-03, with the labels that each got.

#266 Add support for the AWS EFS CSI driver as a k8s add-on
  docs/add-ons/aws-efs-csi-driver.md
  docs/add-ons/index.md
  examples/aws-efs-csi-driver/README.md
  examples/aws-efs-csi-driver/main.tf
  modules/kubernetes-addons/README.md
  modules/kubernetes-addons/aws-efs-csi-driver/README.md
  modules/kubernetes-addons/aws-efs-csi-driver/data.tf
  modules/kubernetes-addons/aws-efs-csi-driver/locals.tf
  modules/kubernetes-addons/aws-efs-csi-driver/main.tf
  modules/kubernetes-addons/aws-efs-csi-driver/outputs.tf
  modules/kubernetes-addons/aws-efs-csi-driver/variables.tf
  modules/kubernetes-addons/locals.tf
  modules/kubernetes-addons/main.tf
  modules/kubernetes-addons/variables.tf
Labels: enhancement

#305 Local context for node groups and fargate
  aws-auth-configmap.tf
  data.tf
  docs/add-ons/kubernetes-dashboard.md
  eks-worker.tf
  examples/analytics/emr-on-eks/README.md
  examples/analytics/emr-on-eks/examples/spark-execute/5-spark-job-with-AMP-AMG.sh
  examples/analytics/emr-on-eks/main.tf
  locals.tf
  main.tf
  modules/aws-eks-fargate-profiles/README.md
  modules/aws-eks-fargate-profiles/data.tf
  modules/aws-eks-fargate-profiles/iam.tf
  modules/aws-eks-fargate-profiles/locals.tf
  modules/aws-eks-fargate-profiles/main.tf
  modules/aws-eks-fargate-profiles/variables.tf
  modules/aws-eks-managed-node-groups/README.md
  modules/aws-eks-managed-node-groups/data.tf
  modules/aws-eks-managed-node-groups/iam.tf
  modules/aws-eks-managed-node-groups/locals.tf
  modules/aws-eks-managed-node-groups/main.tf
  modules/aws-eks-managed-node-groups/managed-launch-templates.tf
  modules/aws-eks-managed-node-groups/outputs.tf
  modules/aws-eks-managed-node-groups/secgroups.tf
  modules/aws-eks-managed-node-groups/variables.tf
  modules/aws-eks-self-managed-node-groups/README.md
  modules/aws-eks-self-managed-node-groups/data.tf
  modules/aws-eks-self-managed-node-groups/iam.tf
  modules/aws-eks-self-managed-node-groups/locals.tf
  modules/aws-eks-self-managed-node-groups/main.tf
  modules/aws-eks-self-managed-node-groups/outputs.tf
  modules/aws-eks-self-managed-node-groups/secgroups.tf
  modules/aws-eks-self-managed-node-groups/self-managed-launch-templates.tf
  modules/aws-eks-self-managed-node-groups/variables.tf
  modules/kubernetes-addons/aws-coredns/variables.tf
  modules/kubernetes-addons/helm-addon/locals.tf
  modules/kubernetes-addons/keda/README.md
  modules/kubernetes-addons/keda/locals.tf
  modules/kubernetes-addons/keda/variables.tf
  modules/kubernetes-addons/kubernetes-dashboard/manifests/eks-admin-service-account.yaml
  modules/launch-templates/main.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: enhancement

#322 New Managed node group example with all the options
  docs/node-groups.md
  examples/argocd/README.md
  examples/argocd/main.tf
  examples/argocd/outputs.tf
  examples/eks-managed-addons/README.md
  examples/eks-managed-addons/main.tf
  examples/fargate-profiles/README.md
  examples/fargate-profiles/main.tf
  examples/fully-private-eks-cluster/README.md
  examples/fully-private-eks-cluster/main.tf
  examples/managed-node-groups/README.md
  examples/managed-node-groups/main.tf
  examples/multi-tenancy-with-teams/README.md
  examples/multi-tenancy-with-teams/main.tf
  examples/multi-tenancy-with-teams/manifests-team-blue/configmap.yaml
  examples/multi-tenancy-with-teams/manifests-team-red/networkpolicy_example.yml
  examples/multi-tenancy-with-teams/outputs.tf
  examples/self-managed-node-groups/README.md
  examples/self-managed-node-groups/main.tf
  examples/windows-node-groups/README.md
  examples/windows-node-groups/k8s/linux-nginx.yaml
  examples/windows-node-groups/k8s/windows-iis-aspnet.yaml
  examples/windows-node-groups/main.tf
Labels: examples

#372 IPv6 VPC CNI Policy hot fix
  modules/kubernetes-addons/aws-vpc-cni/main.tf
Labels: bug
